version: "3.7" 

services:

  db:
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
        
  adminer:
    build: ./adminer
    restart: always
    ports:
      - "6080:8080"
        
  java:
    build: ./src
